Fix image for OpenShift
resource-hub-dev/rhub-app pull request #116
Opened 2022-09-26 11:12 UTC by fpob

2022-09-26 15:00 UTC, thaorell approved these changes

2022-09-26 15:00 UTC, daniellutz approved these changes

2022-09-26 15:03 UTC, brhatiga submitted a review, later dismissed

2022-09-26 19:15 UTC, thaorell requested changes

2022-09-26 19:15 UTC, thaorell commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
I get `#16 0.390 chgrp: changing group of '/opt/app-root/src/index.html': Operation not permitted`

2022-09-27 09:56 UTC, fpob commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
I don't see such error in GitHub pipeline or when I try docker and podman locally. What do you use to build images?

2022-09-27 13:38 UTC, thaorell commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
I'm using Docker on Mac OS X

2022-09-27 14:28 UTC, fpob commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
Probably an issue in MacOS. It is well known that Docker does not work well on non-Linux systems.

2022-09-27 20:27 UTC, thaorell commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
@fpob the github pipeline doesn't use docker build though. I'd like an alternative that works on my computer too if possible

2022-09-27 21:22 UTC, thaorell requested changes

2022-09-27 21:22 UTC, thaorell commented on containers/Dockerfile
> +RUN touch /opt/app-root/src/index.html \
try 
```
USER root
RUN touch /opt/app-root/src/index.html \
    && chgrp 0 /opt/app-root/src/index.html \
    && chmod g=u /opt/app-root/src/index.html
```
I tested this locally on Mac OS X and on stage

2022-09-29 13:30 UTC, thaorell approved these changes

2022-09-29 13:40 UTC, merged