feat: keycloak authentication
resource-hub-dev/rhub-app pull request #13
Opened 2021-04-28 20:27 UTC by thaorell

2021-04-29 07:54 UTC, renanrodrigo reviewed
So, you decided in the end to authenticate the UI directly against Keycloak, instead of going through the API.

2021-04-29 07:54 UTC, renanrodrigo commented on src/services/keycloak.tsx
> +import Keycloak from 'keycloak-js';
You only need the `.tsx` extension for files which include `JSX` components.

2021-04-29 07:54 UTC, renanrodrigo commented on src/services/config.ts
> +  // window.appConfig || {
If window.appConfig is already set (by the index file) it should be there. This should not be commented

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/rootSaga.ts
> +export default function* rootSaga(): any {
If you need to type it, it should be typed as `Generator` (the return type for `all` in this case) , not `any`

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/users/actions.ts
> +export const loginRequest = (payload: { [key: string]: any }) =>
Can't the payload to `loginRequest` be typed?

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/users/actions.ts
> +export const loginSuccess = (payload: any) =>
Same, can't the payload to `loginSuccess` be typed?

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/users/sagas.ts
> +    yield put(loginFailure());
How is this catching the errors you might get when communicating directly to keycloak?

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/users/sagas.ts
> +    const response: { [key: string]: any } = yield call(api.get, 'auth/user', {
cannot we type those `any`s for the responses?

2021-04-29 07:54 UTC, renanrodrigo commented on src/store/ducks/users/sagas.ts
> +export function* getAllUsers() {
What does it mean to get all users?
- It is the same call as the `login` one
- There is no flow to call it
- It does not update the store on success
- It does update the store on failure

2021-04-29 14:03 UTC, thaorell commented on src/store/ducks/rootSaga.ts
> +export default function* rootSaga(): any {
Thanks. I just wanted to silence the VS code warnings

2021-04-29 14:05 UTC, thaorell commented on src/store/ducks/users/sagas.ts
> +export function* getAllUsers() {
This is WIP to test a single API endpoint :smile_cat:

2021-04-29 14:05 UTC, thaorell commented on src/store/ducks/users/sagas.ts
> +    yield put(loginFailure());
this API endpoint could fail if the Token is invalid

2021-04-29 14:05 UTC, thaorell commented on src/store/ducks/users/sagas.ts
> +    const response: { [key: string]: any } = yield call(api.get, 'auth/user', {
yes we can

2021-05-06 16:30 UTC, brhatiga commented
@renanrodrigo sorry was just looking at this and accidentally clicked on the re-review button...

2021-05-07 12:46 UTC, thaorell commented
@renanrodrigo review needed

2021-05-10 17:10 UTC, renanrodrigo requested changes
A couple more quickies

2021-05-10 17:10 UTC, renanrodrigo commented on src/store/ducks/user/index.ts
> +        current: {
You could use the mapper here to ensure consistency

2021-05-10 17:10 UTC, renanrodrigo commented on docker-compose.yml
> +      authUrl: ${SET_URL},
Question: are there reasonable default values for those?

2021-05-10 17:28 UTC, thaorell commented on package.json
> +    "redux-devtools-extension": "^2.13.9",
@renanrodrigo I thought so too but since I'm deploying the devtools in src/store/index.ts it complains and I had to move it to a regular dependency. Same with types

2021-05-10 17:39 UTC, thaorell commented on docker-compose.yml
> +      authUrl: ${SET_URL},
Ah right! Thanks for catching that. For the realm and client, I feel like that should be set by user and not default in this file. What do you think?

2021-05-10 17:54 UTC, thaorell commented on docker-compose.yml
> +      KEYCLOAK_CLIENT: ${SET_CLIENT}
@renanrodrigo open for suggestions here

2021-05-11 15:41 UTC, renanrodrigo requested changes
Just some eslint-disables that are not needed, and should be avoided - promise this is the last one haha

2021-05-11 16:06 UTC, thaorell commented
@renanrodrigo await (Promise)

2021-05-11 17:06 UTC, merged