Add contributing guide
resource-hub-dev/rhub-app pull request #16
Opened 2021-05-06 16:56 UTC by renanrodrigo

## Description:
Add a first version of the contributing guide, with the basic information about PRs and issues.

## Checklist:
 - [ ] Related tests were updated (N/A)
 - [x] Related documentation was updated (it's about the docs anyway haha)

2021-05-06 17:11 UTC, thaorell requested changes

2021-05-06 17:11 UTC, thaorell commented on .github/CONTRIBUTING.md
> +* Fork the project
I think forking the project should be first step

2021-05-07 09:41 UTC, renanrodrigo commented
Also addressed @cbouchar 's comments from the other repo

2021-05-07 11:45 UTC, fpob approved these changes

2021-05-08 14:32 UTC, merged