Added policy dashboard
resource-hub-dev/rhub-app pull request #24
Opened 2021-07-06 16:42 UTC by sai-c

Added the policy UI functionality

2021-07-07 19:37 UTC, thaorell requested changes

2021-07-07 21:41 UTC, sai-c commented on src/components/mainScreen/PageWrapper.tsx
> +        to="/admin_policy"
We would also change the route, but I think that 'admin/policy' route should be defined in the Admin component rather than in MainScreen.tsx. It doesn't seem the Admin component has been defined yet, should I go ahead and create it? Thanks.

2021-07-12 15:01 UTC, thaorell requested changes

2021-07-12 15:01 UTC, thaorell commented on src/components/policies/Policies.tsx
> +  const [captureError, setCaptureError] = useState<boolean>(false);
not sure I understand why this state variable is necessary

2021-07-12 15:14 UTC, sai-c commented on src/components/policies/Policies.tsx
> +  const [captureError, setCaptureError] = useState<boolean>(false);
I'm using the captureError variable, so we don't perform the success/failure actions (like closing the panel/modal) when we load the policy list, or load policy data, but only on create/update/delete.

2021-07-12 17:57 UTC, thaorell requested changes

2021-07-12 17:57 UTC, thaorell commented on src/components/policies/Policies.tsx
> +            <Form key={JSON.stringify(policyView[Number(policyId)], null, 2)}>
@sai-c Not sure if you saw this comment. Any thought? I think we should avoid `JSON.stringify`

2021-07-12 17:57 UTC, thaorell commented on src/components/policies/Policies.tsx
> +        {Object.values(policyView)
same with this

2021-07-12 18:03 UTC, sai-c commented on src/components/policies/Policies.tsx
> +            <Form key={JSON.stringify(policyView[Number(policyId)], null, 2)}>
@thaorell Yep, I added the functionality. Still kept JSON.stringify though, I'll try removing that.

2021-07-12 18:06 UTC, thaorell commented on src/components/policies/Policies.tsx
> +            <Form key={JSON.stringify(policyView[Number(policyId)], null, 2)}>
@sai-c could you point me to where the functionality is?

2021-07-12 18:32 UTC, sai-c commented on src/components/policies/Policies.tsx
> +            <Form key={JSON.stringify(policyView[Number(policyId)], null, 2)}>
Sorry, just forgot to git add before amending & pushing! You should be able to see it now, on lines 64 and 294 onwards in Policies.tsx

2021-07-12 18:54 UTC, sai-c commented on src/components/policies/Policies.tsx
> +        {Object.values(policyView)
New push includes this as well.

2021-07-12 20:12 UTC, thaorell approved these changes

2021-07-12 20:16 UTC, merged