Clusters api
resource-hub-dev/rhub-app pull request #28
Opened 2021-09-14 13:41 UTC by thaorell

## Description:
**Short summary:**
Cluster API set up before Clusterdetails

2021-09-14 14:48 UTC, brhatiga requested changes

2021-09-14 14:48 UTC, brhatiga commented on src/store/ducks/cluster/types.ts
> +// // Data Types - Returned by the API
Should this commented section be removed or is it something you want to use later?

2021-09-16 00:12 UTC, thaorell commented on src/store/ducks/cluster/types.ts
> +// // Data Types - Returned by the API
I'll remove it

2021-09-16 12:20 UTC, brhatiga approved these changes

2021-09-16 12:38 UTC, merged