Add region types, actions, reducers, and sagas
resource-hub-dev/rhub-app pull request #34
Opened 2021-10-21 15:26 UTC by tuananhnguyenf

2021-11-12 15:35 UTC, thaorell commented
@tuananhnguyenf could you rebase and clean up some of the commits? in some commits, you overwrite the code that you wrote earlier. Since this is a new feature, we should avoid that

2021-11-17 19:51 UTC, thaorell commented
@tuananhnguyenf please rename the PR, and solve the merge conflicts

2021-11-17 19:51 UTC, thaorell commented
@tuananhnguyenf please rename the PR, and solve the merge conflicts

2021-11-17 20:00 UTC, thaorell requested changes

2021-11-18 09:30 UTC, tuananhnguyenf commented on src/store/ducks/lab/region/types.ts
> +  name: string;
`LabRegionModel` is used when creating a region. I looked at the form of the request in the [test_region.py](https://github.com/resource-hub-dev/rhub-api/blob/7605ff39e63bad696a6fdee4001c1c3a76175b43/tests/test_api/test_lab/test_region.py#L265) file and took the attributes that are used there. I see now that the request can take more attributes (i.e. all of them except for `id` and `owner_group`). I've already made the changes, should've checked earlier.

The [labRegionDataToState](https://github.com/resource-hub-dev/rhub-app/blob/85c266108acbee28bd99a3a18926b015a03ce241/src/store/ducks/lab/region/index.ts#L14) function is used when listing regions. It takes the response from the api and adds the requested region to the data in the state. I think it shouldn't overwrite the attributes inputted using `LabRegionModel`.

2021-11-18 14:06 UTC, thaorell commented on src/store/ducks/lab/region/types.ts
> +  name: string;
If that's the case. These naming schemes are confusing. If LabRegionModel is _only_ used for create. is it possibly to call it LabRegionCreate, or something clearer?

2021-11-18 17:03 UTC, thaorell commented
@tuananhnguyenf looks good so far. wondering if you could rebase instead of merging the master branch.

2021-11-18 17:13 UTC, thaorell commented on src/store/ducks/lab/region/types.ts
> +export interface Error {
have you tested Errors?

2021-11-18 17:56 UTC, thaorell commented on src/store/ducks/lab/region/actions.ts
> +export const updateRequest = (regionId: number, data: any) =>
could we typecast `data` to any specific type??

2021-11-19 10:37 UTC, tuananhnguyenf commented on src/store/ducks/lab/region/types.ts
> +export interface Error {
Yes, the responses are in that format when a call has an invalid form

2021-11-19 10:39 UTC, tuananhnguyenf commented on src/store/ducks/lab/region/actions.ts
> +export const updateRequest = (regionId: number, data: any) =>
I wasn't sure about the type since almost anything can be updated. Should I create a new type with optional attributes for updating? Similarly to `LabRegionCreate`, so e.g. `LabRegionUpdate`?

2021-11-19 18:10 UTC, thaorell approved these changes

2021-11-19 18:14 UTC, merged