feat: add Products API
resource-hub-dev/rhub-app pull request #39
Opened 2021-11-22 13:27 UTC by thaorell

## Description:
**Short summary:**
Adding product API to comply with rhub-api

2021-11-22 21:50 UTC, brhatiga requested changes

2021-11-22 21:50 UTC, brhatiga commented on src/store/ducks/lab/product/actions.ts
> +  parameters?: { [key: string]: string | number }
Do you think renaming "parameters" to "htmlParams" would make sense?

2021-11-23 14:49 UTC, thaorell commented on src/store/ducks/lab/product/actions.ts
> +  parameters?: { [key: string]: string | number }
Yes that would be smart!

2021-11-23 15:21 UTC, brhatiga approved these changes

2021-11-23 15:48 UTC, merged