Add a setup form for creating and editing policies
resource-hub-dev/rhub-app pull request #59
Opened 2022-02-23 16:31 UTC by tuananhnguyenf

## Description:
**Short summary:**
These changes replace the original UI for creating and editing a policy which used a text box and relied on the user to input a valid JSON. The new UI uses a form and is validated using React Hook Form.
### Creating a policy - old UI:
![create_policy_old](https://user-images.githubusercontent.com/79764417/155362418-fce07c52-88eb-4b5d-97f2-b38784172b16.png)
### Creating a policy - form:
![create_policy_form](https://user-images.githubusercontent.com/79764417/155362403-fac7665e-fec5-4f7d-8b1e-a279f26710f2.png)
### Editing a policy - old UI:
![edit_policy_old](https://user-images.githubusercontent.com/79764417/155362424-fe459b2a-125e-4f46-8809-d6290729e2e5.png)
### Editing a policy - new UI:
![edit_policy_form](https://user-images.githubusercontent.com/79764417/155362422-0387045d-004f-40f7-b18c-dfbcba0461f6.png)

2022-03-02 19:43 UTC, thaorell reviewed
Couple of changes. I'll need to review more.

2022-03-02 19:43 UTC, thaorell commented on src/components/policies/Policies.tsx
> +  const getDefaultFormValues = (): PolicyFormData => ({
This seems like a duplicate of [this](https://github.com/resource-hub-dev/rhub-app/blob/471e12a2c77e088f8a5b9e842255a946092d915b/src/store/ducks/lab/policy/index.ts#L12)

2022-03-02 19:43 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  schedAvailEnabled: boolean;
This seems like a duplicate of [type](https://github.com/resource-hub-dev/rhub-app/blob/master/src/store/ducks/lab/policy/types.ts#L33).

2022-03-02 19:43 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  const locationOptions = [
Not sure about hard-coding it here. Let's abstract this out to a different `.ts` file.

2022-03-02 19:43 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  const locationOptions = [
Better yet, propose a change in the API and DB

2022-03-07 10:44 UTC, tuananhnguyenf commented on src/components/policies/Policies.tsx
> +  const getDefaultFormValues = (): PolicyFormData => ({
This function takes values from the existing policy that a user selects and puts them into a format of the default values of the form. It has all of the fields that that are used by all registered inputs in React Hook Form.

2022-03-07 10:51 UTC, tuananhnguyenf commented on src/components/policies/PolicyForm.tsx
> +  schedAvailEnabled: boolean;
While it is similar, there are differences. Namely, the constraints aren't nested in a `constraint` object, tag and limit have a different format (an array of one-property objects instead of an array of strings and an array of two-property objects instead of an object respectively) among others. It also contains all of the values used for enabling/disabling various constraints.
All of the fields in the type are used by the registered inputs in the `PolicyForm`

2022-03-14 17:53 UTC, thaorell requested changes

2022-03-14 17:53 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  const watchLocationEnabled = watch('locationEnabled');
Is there a reason why you use these watch calls? Use [getValues](https://react-hook-form.com/api/useform/getvalues), as `watch` triggers re-renders and has worse performance

2022-03-14 17:53 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  schedAvailEnabled: boolean;
The enabled/disabled fields should be a different type. Arrays of one-property objects with indices as keys are in fact arrays in JS/TS [read more](https://www.w3schools.com/js/js_arrays.asp#:~:text=Arrays%20are%20a%20special%20type,are%20best%20described%20as%20arrays.), so maybe we should use arrays?

2022-03-14 17:53 UTC, thaorell commented on src/components/policies/PolicyForm.tsx
> +  schedAvailEnabled: boolean;
The enabled/disabled fields should be a different type. Arrays of one-property objects with indices as keys are in fact arrays in JS/TS [read more](https://www.w3schools.com/js/js_arrays.asp#:~:text=Arrays%20are%20a%20special%20type,are%20best%20described%20as%20arrays.), so maybe we should use arrays?

2022-04-21 16:00 UTC, tuananhnguyenf commented on src/components/policies/PolicyForm.tsx
> +  const watchLocationEnabled = watch('locationEnabled');
I've added a commit that limits re-rendering to the expandable part of the form (constraints part) instead of the whole form. Will try to think of ways to reduce re-renders to individual form groups but currently I think the "Disable All" button is complicating it by a bit.

2022-04-22 15:13 UTC, thaorell commented
I just wrote code for lab/location in #91. After that, you can fix and rebase your code where location applies

2022-08-23 19:14 UTC, closed without merging