feat: use node v16, v17 for CI
resource-hub-dev/rhub-app pull request #73
Opened 2022-03-11 16:28 UTC by thaorell

## Description:
Use latest node versions for validate

## Checklist:
 - [X] Related tests were updated
 - [X] Related documentation was updated

2022-03-11 18:51 UTC, daniellutz submitted a review, later dismissed

2022-03-14 14:49 UTC, thaorell commented
@daniellutz node17 isn't supported by RH yet. So I've decided to keep with Node 16 for now

2022-03-14 15:58 UTC, daniellutz approved these changes

2022-03-14 16:45 UTC, brhatiga requested changes

2022-03-14 16:45 UTC, brhatiga commented on Dockerfile.dev
> +FROM node:16
Can we specify pulling the image from RH here as well?   registry.access.redhat.com/ubi8/nodejs-16

2022-03-14 17:28 UTC, thaorell commented on Dockerfile.dev
> +FROM node:16
actually the RH image doesn't work in the dev environment, due to RH's images tend to gear for productions and we will need to put extra vars and make it work the same as the image from Nodejs directly. Since we have to tweak to get the same results, I think we should just go ahead and get directly from Nodejs.

2022-03-14 18:21 UTC, brhatiga approved these changes

2022-03-14 18:30 UTC, merged