Components quick cluster wizard tests
resource-hub-dev/rhub-app pull request #83
Opened 2022-03-29 15:24 UTC by simonkosina

## Description:
**Short summary:**
Adding tests for the `QuickClusterWizard` component and all the components in the `src/components/QuickClusterWizard/steps` directory.

2022-03-31 15:49 UTC, thaorell requested changes

2022-03-31 15:49 UTC, thaorell commented on __mocks__/labRegion.ts
> +  region: {
To avoid this region being copied and pasted. Try
```
export const noLocationProductRegionExample : RegionsWithProduct = {
  enabled: true,
  product_id: 1,
  region: { ...regionExample, location: null },
};
```

2022-03-31 15:49 UTC, thaorell commented on __mocks__/labRegion.ts
> +export const noUserQuotaProductRegionExample: RegionsWithProduct = {
same here. continue using spread operator to avoid duplicating code :)

2022-04-04 06:01 UTC, simonkosina commented on __mocks__/labRegion.ts
> +export const noUserQuotaProductRegionExample: RegionsWithProduct = {
Sorry for that! It should be good now :)

2022-04-04 12:16 UTC, merged